apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-frontend
  template:
    metadata:
      labels:
        app: notes-frontend
    spec:
      containers:
      - name: notes-frontend
        image: hirentimbadiya/notes-frontend
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_BACKEND_HOST
          valueFrom:
            secretKeyRef:
              name: host-url
              key: inote-host-url
