replicaCount: 1
image:
  repository: hirentimbadiya/notes-frontend
  pullPolicy: IfNotPresent
service:
  name: notes-frontend
  type: NodePort
  port: 80
  targetPort: 3000
secrets:
  mongo:
    envName: REACT_APP_BACKEND_HOST
    secretName: host-url
    key: inote-host-url
