@Library('notesapp-devops') _
pipeline {
    agent any
    environment {
        RELEASE_NAME = "notes-backend"
        IMAGE_NAME = "hirentimbadiya/notes-backend"
        SONAR_INSTALLATION_NAME = "SonarQube"
    }
    stages {
        stage('Scanning, Building and Deploying') {
            script {
                pipeline_server(imageName: IMAGE_NAME, releaseName: RELEASE_NAME, installationName: SONAR_INSTALLATION_NAME)
            }
        }
    }
}