pipeline {
    agent any
    stages {
        stage('Git Checkout') {
            steps {
                script {
                    checkout scmGit(branches: [[name: '*/main']], extensions: [], gitTool: 'Default', userRemoteConfigs: [[credentialsId: 'notes-github', url: 'git@github.com:hirentimbadiya/notes-devops.git']])
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    bat """
                    cd server
                    docker build -t hirentimbadiya/notes-backend .
                    """
                }
            }
        }

        stage('Login To DockerHub') {
            steps {
                withCredentials([string(credentialsId: 'dockerhub', variable: 'dockerhub_password')]) {
                    bat """
                    docker logout
                    docker login -u hirentimbadiya -p ${dockerhub_password}
                    """
                }
            }
        }

        stage("Push Image To DockerHub") {
            steps {
                script {
                    bat 'docker push hirentimbadiya/notes-backend'
                }
            }
        }

        stage("Deploy To Kubernetes") {
            steps {
                script {
                    withKubeConfig(caCertificate: '', clusterName: 'gke_gcp-learning-417116_us-central1-c_main-cluster', contextName: '', credentialsId: 'k8s-cred', namespace: 'jenkins', restrictKubeConfigAccess: true, serverUrl: 'https://35.226.254.176') {
                        bat """
                        cd server
                        kubectl apply -f deployment.yaml
                        """
                    }
                }
            }
        }
    }
}