replicaCount: 1
image:
  repository: hirentimbadiya/notes-backend
  pullPolicy: IfNotPresent
service:
  name: notesapp-backend
  type: NodePort
  port: 80
  targetPort: 3001
secrets:
  mongo:
    envName: MONGODB_URI
    secretName: mongo-secret
    key: mongo-uri
  jwt:
    envName: JWT_SECRET
    secretName: jwt-secret
    key: jwt-secret
